<a href="https://colab.research.google.com/github/anuragsinghbhandari/Create_Matrix/blob/main/Create_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries
import numpy as np


In [13]:
#creating a square matrix of size n
n =int(input("Enter the size of square matrix: "))
Matrix_A = np.ones((n,n), dtype=np.int64)

Enter the size of square matrix: 2


In [14]:
for i in range(0, n):
  for j in range(0, n):
    Matrix_A[i,j]=int(input("Enter a"+str(i+1)+str(j+1)+": "))
print(Matrix_A)


Enter a11: 1
Enter a12: 2
Enter a21: 3
Enter a22: 4
[[1 2]
 [3 4]]


In [15]:
#integrating it in a function
def create_matrix(matrix_name, size):
  matrix_name = np.ones((size,size), dtype=np.int64)
  for i in range(0, size):
    for j in range(0, size):
      matrix_name[i,j]=int(input("Enter a"+str(i+1)+str(j+1)+": "))
  return matrix_name


In [17]:
#trying the create_matrix function
A = create_matrix("A", 3)
print(A)


Enter a11: 11
Enter a12: 12
Enter a13: 13
Enter a21: 14
Enter a22: 15
Enter a23: 16
Enter a31: 17
Enter a32: 18
Enter a33: 19
[[11 12 13]
 [14 15 16]
 [17 18 19]]
